FROM ghcr.io/puppeteer/puppeteer:23.4.1

USER root

WORKDIR /app

COPY package*.json ./
RUN npm install --production  # <--- troca ci por install

COPY . .

RUN mkdir -p /app/prints

ENV DISPLAY=:99
CMD ["xvfb-run", "--server-args=-screen 0 1280x800x24", "npm", "start"]
