FROM ghcr.io/puppeteer/puppeteer:23.4.1

USER root

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

RUN mkdir -p /app/prints

# Sem xvfb-run - a imagem oficial suporta headless direto
ENV DISPLAY=:99
CMD ["npm", "start"]
